name: ksm_tanjung
description: Aplikasi administrasi KSM Tanjung

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  fl_chart: ^1.1.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  dio: ^5.4.0
  path_provider: ^2.1.2
  open_filex: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/qr.jpg
    - assets/ksmlogo.png
    - assets/wa.png
